name: facebook_pojo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: "^0.14.1"


flutter_native_splash:
  color: "#ffffff"
  image: assets/logos/facebookLogo.png
  branding: assets/logos/New Project.png
  branding_mode: bottom
  branding_bottom_padding: 24
  color_dark: "#121212"
  image_dark: assets/logos/facebookLogo.png
  branding_dark: assets/logos/New Project.png

  android_12:
    image: assets/logos/facebookLogo.png
    image_dark: assets/logos/facebookLogo.png
    branding: assets/logos/New Project.png
    branding_mode: bottom
    branding_bottom_padding: 24
    branding_dark: assets/logos/New Project.png


flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/logos/
  - assets/images/
  - assets/icons/
  - assets/images/post/
  - assets/images/profile/
  - assets/images/stories_images/